# Sonar projectKey and organization are injected dynamically in GitHub Actions

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=wishboard
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src,scripts,aws-serverless

# Coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude tests, mock data, and entry points from being analyzed as production code
sonar.exclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx,**/main.tsx,aws-serverless/post-build.js

# Increase Node.js memory for TS/JS analysis to prevent hanging
sonar.javascript.node.maxspace=4096

# Explicitly specify tsconfig.json location
sonar.typescript.tsconfigPath=tsconfig.json

# Exclude difficult-to-test components, entry points, and test setup files from coverage
sonar.coverage.exclusions=src/client/src/main.tsx


# Exclude data tables from CPD if needed

