import React from 'react';
import IdentityStickers from './IdentityStickers';
import FlagButton from './FlagButton';
import { useTextFit } from '../hooks/useTextFit';

interface Contact {
  type: string;
  value: string;
}

export interface Wish {
  id: string;
  content: string;
  creator_attributes?: Record<string, string[]>;
  contacts?: Contact[];
  wishmail_enabled?: boolean;
  image_url?: string;
  image_id?: string;
}

function getSafeImageUrl(url?: string): string | undefined {
  if (!url) return undefined;
  const trimmed = url.trim();

  // 1. Safe relative paths (e.g. from image_id)
  if (trimmed.startsWith('/images/')) {
    // Prevent path traversal or protocol-relative bypasses
    if (trimmed.includes('..') || trimmed.startsWith('//')) {
      return undefined;
    }
    return encodeURI(trimmed);
  }

  // 2. Safe blob URLs (generated by URL.createObjectURL)
  if (trimmed.startsWith('blob:http://') || trimmed.startsWith('blob:https://')) {
    return encodeURI(trimmed);
  }

  // 3. Safe data URIs for images
  if (trimmed.startsWith('data:image/')) {
    return encodeURI(trimmed);
  }

  return undefined;
}

function sanitizeImageId(imageId?: string): string {
  if (!imageId) return '';
  // Restrict to filename-safe characters to avoid path/protocol injection.
  return imageId.replace(/[^a-zA-Z0-9._-]/g, '');
}

function getSafeImageSrc(wish: Wish): string | undefined {
  const safeUrl = getSafeImageUrl(wish.image_url);
  if (safeUrl) {
    return safeUrl;
  }

  const safeImageId = sanitizeImageId(wish.image_id);
  const serverImagePath = safeImageId ? `/images/${safeImageId}` : '';
  return getSafeImageUrl(serverImagePath);
}

interface WishCardProps {
  wish: Wish;
  cardClass?: 'wish-card' | 'display-card';
  showFlag?: boolean;
  onFlag?: (id: string) => void;
  onSendMail?: (id: string) => void;
  onOverflowChange?: (isOverflowing: boolean) => void;
  isEditorPreview?: boolean;
  onAdminDelete?: (id: string) => void;
  onExclude?: (id: string) => void;
  onUnexclude?: (id: string) => void;
  isExcluded?: boolean;
  onEdit?: (id: string) => void;
  onDelete?: (id: string) => void;
  onViewWishmail?: (id: string) => void;
  unreadWishmailCount?: number;
}

function ExcludeToggleButton({
  wishId,
  isExcluded,
  onExclude,
  onUnexclude,
}: Readonly<{
  wishId: string;
  isExcluded: boolean;
  onExclude: (id: string) => void;
  onUnexclude?: (id: string) => void;
}>) {
  const handleClick = () => {
    if (isExcluded && onUnexclude) {
      onUnexclude(wishId);
    } else {
      onExclude(wishId);
    }
  };
  return (
    <button
      type="button"
      className="exclude-wish-btn"
      onClick={handleClick}
      title={isExcluded ? 'Unhide wish' : 'Hide wish / Not interested'}
    >
      {isExcluded ? (
        <span className="emoji-icon" aria-hidden="true">
          👁
        </span>
      ) : (
        <svg
          viewBox="0 0 24 24"
          stroke="currentColor"
          strokeWidth="2"
          fill="none"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24" />
          <line x1="1" y1="1" x2="23" y2="23" />
        </svg>
      )}
    </button>
  );
}

function WishBottomActions({
  hasBottomActions,
  wish,
  onViewWishmail,
  onSendMail,
  unreadWishmailCount,
}: Readonly<{
  hasBottomActions: boolean;
  wish: Wish;
  onViewWishmail?: (id: string) => void;
  onSendMail?: (id: string) => void;
  unreadWishmailCount?: number;
}>) {
  if (!hasBottomActions) return null;
  return (
    <>
      {wish.contacts && wish.contacts.length > 0 && (
        <div className="wish-contacts-list">
          {wish.contacts.map((c, i) => (
            <span key={`${c.type}-${i}`} className="wish-contact-item">
              <strong>{c.type}:</strong> {c.value}
            </span>
          ))}
        </div>
      )}

      {(wish.wishmail_enabled || onViewWishmail) && (
        <button
          type="button"
          className="send-mail-icon-btn"
          onClick={(e) => {
            e.preventDefault();
            if (onViewWishmail) {
              onViewWishmail(wish.id);
            } else if (onSendMail) {
              onSendMail(wish.id);
            }
          }}
          title={onViewWishmail ? 'View Wishmail' : 'Send Wishmail'}
          aria-label={onViewWishmail ? 'View Wishmail' : 'Send Wishmail'}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <rect width="20" height="16" x="2" y="4" rx="2" />
            <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
          </svg>
          {onViewWishmail && unreadWishmailCount !== undefined && unreadWishmailCount > 0 && (
            <div className="mail-unread-dot" title={`${unreadWishmailCount} unread message(s)`} />
          )}
        </button>
      )}
    </>
  );
}

function WishTopActions({
  wishId,
  isExcluded,
  showFlag,
  onFlag,
  onExclude,
  onUnexclude,
  onEdit,
  onDelete,
  onAdminDelete,
}: Readonly<{
  wishId: string;
  isExcluded: boolean;
  showFlag?: boolean;
  onFlag?: (id: string) => void;
  onExclude?: (id: string) => void;
  onUnexclude?: (id: string) => void;
  onEdit?: (id: string) => void;
  onDelete?: (id: string) => void;
  onAdminDelete?: (id: string) => void;
}>) {
  return (
    <div className="card-top-left-actions">
      {showFlag && onFlag && <FlagButton onFlag={() => onFlag(wishId)} />}
      {onExclude && (
        <ExcludeToggleButton
          wishId={wishId}
          isExcluded={isExcluded}
          onExclude={onExclude}
          onUnexclude={onUnexclude}
        />
      )}
      {onEdit && (
        <button
          type="button"
          className="owner-edit-wish-btn"
          onClick={() => onEdit(wishId)}
          title="Edit Wish"
        >
          <svg
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth="2.5"
            fill="none"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
            <path d="M18.5 2.5a2.121 2.121 0 1 1 3 3L12 15l-4 1 1-4Z" />
          </svg>
        </button>
      )}
      {onDelete && (
        <button
          type="button"
          className="owner-delete-wish-btn"
          onClick={() => onDelete(wishId)}
          title="Delete Wish"
        >
          <svg
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth="2.5"
            fill="none"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <polyline points="3 6 5 6 21 6" />
            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
          </svg>
        </button>
      )}
      {onAdminDelete && (
        <button
          type="button"
          className="admin-delete-wish-btn"
          onClick={() => onAdminDelete(wishId)}
          title="Admin Delete Wish"
        >
          <svg
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth="2.5"
            fill="none"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <polyline points="3 6 5 6 21 6" />
            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
          </svg>
        </button>
      )}
    </div>
  );
}

export default function WishCard({
  wish,
  cardClass = 'wish-card',
  showFlag = true,
  onFlag,
  onSendMail,
  onOverflowChange,
  isEditorPreview = false,
  onAdminDelete,
  onExclude,
  onUnexclude,
  isExcluded = false,
  onEdit,
  onDelete,
  onViewWishmail,
  unreadWishmailCount,
}: Readonly<WishCardProps>) {
  const hasBottomActions = Boolean(
    (wish.contacts && wish.contacts.length > 0) || wish.wishmail_enabled || onViewWishmail
  );
  const showTopActions = Boolean(
    (showFlag && onFlag) || onExclude || onAdminDelete || onEdit || onDelete
  );

  // Use lower max font size for the card, and minimum 10px so we have enough room to scale down
  const { containerRef, contentRef, isOverflowing } = useTextFit<
    HTMLDivElement,
    HTMLParagraphElement
  >(
    {
      minFontSize: 10,
      maxFontSize: cardClass === 'display-card' ? 36 : 18,
      step: 1,
      // When shown as an editor preview the rendered card may be much smaller
      // than a real search-result card (especially on mobile). Pass the notional
      // content area of the minimum real card (280px grid column, 5:3 ratio,
      // padding 16/18/18/18) so the overflow warning fires based on real-world fit.
      notionalSize: isEditorPreview ? { width: 244, height: 134 } : undefined,
    },
    [wish]
  );

  React.useEffect(() => {
    if (onOverflowChange) {
      onOverflowChange(isOverflowing);
    }
  }, [isOverflowing, onOverflowChange]);

  const hasImage = Boolean(wish.image_url || wish.image_id);

  return (
    <article
      className={`${cardClass} ${hasImage ? 'card-has-image' : ''} ${isExcluded ? 'is-excluded' : ''} ${isOverflowing && isEditorPreview ? 'text-overflow-hint' : ''}`}
      key={wish.id}
      style={isExcluded ? { opacity: 0.6 } : {}}
    >
      <div
        className={`wish-card-inner-scale ${hasImage ? 'has-image' : ''}`}
        ref={containerRef}
        style={
          hasImage
            ? { position: 'relative', height: '100%', padding: 0 }
            : {
                position: 'relative',
                flex: '1 1 auto',
                minHeight: 0,
                overflow: 'hidden',
              }
        }
      >
        {!hasImage && <IdentityStickers attributes={wish.creator_attributes} />}

        {showTopActions && (
          <WishTopActions
            wishId={wish.id}
            isExcluded={isExcluded}
            showFlag={showFlag}
            onFlag={onFlag}
            onExclude={onExclude}
            onUnexclude={onUnexclude}
            onEdit={onEdit}
            onDelete={onDelete}
            onAdminDelete={onAdminDelete}
          />
        )}

        {hasImage ? (
          <div style={{ width: '100%', height: '100%', position: 'relative' }}>
            <img
              src={getSafeImageSrc(wish)}
              alt={wish.content || 'Handwritten wish'}
              style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }}
            />
            <div
              style={{ position: 'absolute', top: '0', right: '6px', zIndex: 5, fontSize: '10px' }}
            >
              <IdentityStickers attributes={wish.creator_attributes} />
            </div>
            {/* Hidden text for accessibility/search */}
            <p className="sr-only" style={{ display: 'none' }}>
              {wish.content}
            </p>
            <WishBottomActions
              hasBottomActions={hasBottomActions}
              wish={wish}
              onViewWishmail={onViewWishmail}
              onSendMail={onSendMail}
              unreadWishmailCount={unreadWishmailCount}
            />
          </div>
        ) : (
          <p className="wish-text" ref={contentRef}>
            {wish.content}
          </p>
        )}
      </div>

      {!hasImage && hasBottomActions && (
        <div style={{ position: 'relative', flex: '0 0 2.2em', marginTop: '4px' }}>
          <WishBottomActions
            hasBottomActions={hasBottomActions}
            wish={wish}
            onViewWishmail={onViewWishmail}
            onSendMail={onSendMail}
            unreadWishmailCount={unreadWishmailCount}
          />
        </div>
      )}
    </article>
  );
}
